name: Check PR Title
on:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "edited"
      - "synchronize"
jobs:
  lint_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
